### PR TITLE
Rename completion scripts according to each shell conventions

### LINKED ISSUE #451: Split the completions directory and rename scripts according to conventions of each shell
First of all, thanks a lot for this great tool!

Would it be possible to split the [`/contrib`](/ogham/exa/tree/master/contrib) subdirectory for each shell? This way, I could add the completions script easily via [antigen](/zsh-users/antigen): `antigen bundle ogham/exa contrib/completions/zsh`.

Thanks again!

### PR DESCRIPTION
**Pull request by ariasuni**
Fix #451 

```
renamed:         completions/completions.bash -> completions/bash/exa
renamed:         completions/completions.fish -> completions/fish/exa.fish
remaned:         completions/completions.zsh -> completions/zsh/_exa
```

### CODE REVIEW

**Comment by ariasuni** [comment]
I’ll merge this now, because the website’s links are already broken and this is tracked at #757 anyway.

**Comment by timbedard** [comment]
Heads up: This breaks Homebrew `--HEAD` installation. We'll need to add a check of some sort to [the formula](https://github.com/Homebrew/homebrew-core/blob/11d3369762a7eccf2349eefc732ffe183cb0ba13/Formula/exa.rb) to determine where to find the completions.

**Comment by ariasuni** [comment]
@timbedard Should I open an issue there? I wouldn’t be comfortable making a PR I couldn’t test, and the changes are trivial so…

**Comment by timbedard** [comment]
@ariasuni I usually pull up [this guide](https://docs.brew.sh/How-To-Open-a-Homebrew-Pull-Request) when I need to open a PR for Homebrew. It's not hard to run the existing tests and it's outlined in that guide.

**Comment by ariasuni** [comment]
Well to be honest I don’t how `--HEAD` works and how to not break it for users of the stable version, and it certainly looks like someone who uses brew should open the issues since it requests output from `brew` and warns about not filling the template. And I couldn’t make brew works on my (Linux) system last time I tried and it was a mess so, eh.

**Comment by timbedard** [comment]
Gotcha. I'll try to give it a go sometime this week when I have time.

**Pull request merged**
