### PR TITLE
Display Makefile icon for .mk files

### PR DESCRIPTION
**Pull request by joshuagawley**
Displays the Makefile icon for .mk files, as desired by #916 .

### CODE REVIEW

**Comment by ariasuni** [comment]
Well, I don’t agree with the icon for `Makefile`, there are other implementations than GNU make, like BSD make or nmake used in Visual Studio ([according to Wikipedia](https://en.wikipedia.org/wiki/Make_(software))).

I tried searching for an alternative icon that carries the meaning of a task runner or something, but I couldn’t find one I’m satisfied with… (you can see them here: https://www.nerdfonts.com/cheat-sheet)

**Comment by ariasuni** [comment]
What about `\u{f489}` (` `, `nf-oct-terminal`), since a `Makefile` is designed to run shell commands?

**Comment by joshuagawley** [comment]
Apologies for the delay; I had changed my username in the meantime and so my commit history is somewhat unclean (the real change is in the second commit, where I changed the icon to the terminal icon).

**Comment by ariasuni** [comment]
Could you rebase your work, or cherry-pick your commits on top of master? I’m not sure I want to merge those 18 commits. :sweat_smile:

**Comment by ariasuni** [comment]
#945 was merged instead.

**Comment by Freed-Wu** [comment]
> What about `\u{f489}` (` `, `nf-oct-terminal`), since a `Makefile` is designed to run shell commands?

How about  `\u{eb6d}`,  `\u{e20f}`,  `\u{f425}`? Makefile is not shell, Use same icon as shell is confusing. A icon containing tool may be good.

**Pull request closed without merging**
