### PR TITLE
Update dependencies

### PR DESCRIPTION
**Pull request by Stebalien**
* Also remove bitflags as it isn't used.
* Don't update ansi_term as ANSIString is no longer Clone.

Note: This fixes an openssl build problem I was having (two conflicting openssl versions).

### CODE REVIEW

**Comment by emintham** [comment]
I had the same issue with building on Ubuntu 16.04. The versions in this MR does fix the issue.

**Comment by iKevinY** [comment]
Interestingly, this problem doesn't seem to occur on macOS.

**Comment by ogham** [comment]
Thanks (y)

**Comment by ogham** [comment]
Thanks 👍

**Pull request merged**
