### PR TITLE
Fix clippy warnings and explicitely ignore a few, fix future deprecation

### PR DESCRIPTION
**Pull request by ariasuni**
Now, clippy doesn’t show any warning.

### CODE REVIEW

**Comment by ariasuni** [comment]
I just saw somebody already made a PR for the update to Rust 2018, so just adding my other fixes here.

**Comment by ogham** [comment]
I don't know which set of Clippy lints you used but I agree with all the changes made here. Hopefully I haven't introduced any new things to fix in the meantime. Thank you again.

**Comment by ariasuni** [comment]
I used the default lints. No problem, exa has been one of the most enjoyable code base to work, I guess partly thanks to Rust but still I found the code easy to browse and modify. :)

**Comment by ogham** [comment]
That's extremely good to hear :)

**Pull request merged**
