### PR TITLE
Add xattr for linux

### PR DESCRIPTION
**Pull request by nwin**
I made it as a separate PR since I’m not sure if this is the way to go or if we need to introduce a feature since linux might not have extended attributes built into the kernel but I think this is common.

### CODE REVIEW

**Comment by ogham** [comment]
Does this completely supersede #14?

**Comment by nwin** [comment]
Yes this branch is based on the other one.

**Comment by ogham** [comment]
I tested this on OS X and Linux - all good.

**Comment by ogham** [comment]
I changed the pre-calculated width of the permissions column from 10 to 11 to account for the new @ character.

**Pull request merged**
