### PR TITLE
Add threading around std::fs::symlink_metadata

### PR DESCRIPTION
**Pull request by saethlin**
The lstat system call that is used to implement `std::fs::symlink_metadata` is very slow on some filesystems; namely the lustre filesystem that I spend a lot of time on. For my large directories when the filesystem cache is cold (which is a quite common case for this kind of program) this brings the runtime of exa down from 14s to 0.5s.

I'd be quite interested to know if these changes have a measurable impact impact on anyone else's usage.

### CODE REVIEW

**Comment by thomasf** [comment]
I have also bumped in to this issue with exa on some networked file systems where ls takes like half a second and exa takes up to 10 seconds to complete for the same wide view. 

I think we need tests for this. there should be some simulated fuse file system out there that  exhibit the same "bad" behavior in a repeatable way. 

If we just take a very simplistic overview it seems like exa is "wasting" time on doing syscalls it doesht have to.. 

```
▶22 ~/tmp/test
:49 tf@whale$ ls
hello.c  profile.zip                                   profile.zip.2019-12-19T01-03-14.950275+01-00  symling
main.go  profile.zip.2019-12-19T00-58-55.600109+01-00  profiling-127.0.0.1:9000.pprof
▶22 ~/tmp/test
:49 tf@whale$ exa
hello.c  profile.zip                                   profile.zip.2019-12-19T01-03-14.950275+01-00  symling
main.go  profile.zip.2019-12-19T00-58-55.600109+01-00  profiling-127.0.0.1:9000.pprof
▶22 ~/tmp/test
:49 tf@whale$ strace ls 2>&1 | grep stat
fstat(3, {st_mode=S_IFREG|0644, st_size=237735, ...}) = 0
fstat(3, {st_mode=S_IFREG|0644, st_size=163240, ...}) = 0
fstat(3, {st_mode=S_IFREG|0755, st_size=2025032, ...}) = 0
fstat(3, {st_mode=S_IFREG|0644, st_size=539176, ...}) = 0
fstat(3, {st_mode=S_IFREG|0644, st_size=18816, ...}) = 0
fstat(3, {st_mode=S_IFREG|0755, st_size=158288, ...}) = 0
statfs("/sys/fs/selinux", 0x7ffee96fb980) = -1 ENOENT (No such file or directory)
statfs("/selinux", 0x7ffee96fb980)      = -1 ENOENT (No such file or directory)
fstat(3, {st_mode=S_IFREG|0444, st_size=0, ...}) = 0
fstat(3, {st_mode=S_IFREG|0644, st_size=8634688, ...}) = 0
fstat(3, {st_mode=S_IFDIR|0775, st_size=4096, ...}) = 0
fstat(1, {st_mode=S_IFIFO|0600, st_size=0, ...}) = 0
▶22 ~/tmp/test
:49 tf@whale$ strace exa 2>&1 | grep stat
fstat(3, {st_mode=S_IFREG|0644, st_size=237735, ...}) = 0
fstat(3, {st_mode=S_IFREG|0644, st_size=108928, ...}) = 0
fstat(3, {st_mode=S_IFREG|0644, st_size=18816, ...}) = 0
fstat(3, {st_mode=S_IFREG|0755, st_size=158288, ...}) = 0
fstat(3, {st_mode=S_IFREG|0644, st_size=100888, ...}) = 0
fstat(3, {st_mode=S_IFREG|0755, st_size=2025032, ...}) = 0
fstat(3, {st_mode=S_IFREG|0444, st_size=0, ...}) = 0
statx(0, NULL, AT_STATX_SYNC_AS_STAT, STATX_ALL, NULL) = -1 EFAULT (Bad address)
statx(AT_FDCWD, ".", AT_STATX_SYNC_AS_STAT|AT_SYMLINK_NOFOLLOW, STATX_ALL, {stx_mask=STATX_ALL, stx_attributes=0, stx_mode=S_IFDIR|0775, stx_size=4096, ...}) = 0
fstat(3, {st_mode=S_IFDIR|0775, st_size=4096, ...}) = 0
statx(AT_FDCWD, "./profile.zip.2019-12-19T00-58-55.600109+01-00", AT_STATX_SYNC_AS_STAT|AT_SYMLINK_NOFOLLOW, STATX_ALL, {stx_mask=STATX_ALL, stx_attributes=0, stx_mode=S_IFREG|0664, stx_size=379, ...}) = 0
statx(AT_FDCWD, "./main.go", AT_STATX_SYNC_AS_STAT|AT_SYMLINK_NOFOLLOW, STATX_ALL, {stx_mask=STATX_ALL, stx_attributes=0, stx_mode=S_IFREG|0664, stx_size=532, ...}) = 0
statx(AT_FDCWD, "./profile.zip.2019-12-19T01-03-14.950275+01-00", AT_STATX_SYNC_AS_STAT|AT_SYMLINK_NOFOLLOW, STATX_ALL, {stx_mask=STATX_ALL, stx_attributes=0, stx_mode=S_IFREG|0664, stx_size=23985, ...}) = 0
statx(AT_FDCWD, "./profile.zip", AT_STATX_SYNC_AS_STAT|AT_SYMLINK_NOFOLLOW, STATX_ALL, {stx_mask=STATX_ALL, stx_attributes=0, stx_mode=S_IFREG|0664, stx_size=56998, ...}) = 0
statx(AT_FDCWD, "./symling", AT_STATX_SYNC_AS_STAT|AT_SYMLINK_NOFOLLOW, STATX_ALL, {stx_mask=STATX_ALL, stx_attributes=0, stx_mode=S_IFLNK|0777, stx_size=11, ...}) = 0
statx(AT_FDCWD, "./profiling-127.0.0.1:9000.pprof", AT_STATX_SYNC_AS_STAT|AT_SYMLINK_NOFOLLOW, STATX_ALL, {stx_mask=STATX_ALL, stx_attributes=0, stx_mode=S_IFREG|0600, stx_size=56824, ...}) = 0
statx(AT_FDCWD, "./hello.c", AT_STATX_SYNC_AS_STAT|AT_SYMLINK_NOFOLLOW, STATX_ALL, {stx_mask=STATX_ALL, stx_attributes=0, stx_mode=S_IFREG|0664, stx_size=86, ...}) = 0
statx(AT_FDCWD, "./profile.zip", AT_STATX_SYNC_AS_STAT, STATX_ALL, {stx_mask=STATX_ALL, stx_attributes=0, stx_mode=S_IFREG|0664, stx_size=56998, ...}) = 0
▶22 ~/tmp/test
:49 tf@whale$ ll
.rw-rw-r--  86 thomasf 23 Jan 22:47 hello.c
.rw-rw-r-- 532 thomasf 23 Jan 22:47 main.go
.rw-rw-r-- 56k thomasf 23 Jan 22:47 profile.zip
.rw-rw-r-- 379 thomasf 23 Jan 22:47 profile.zip.2019-12-19T00-58-55.600109+01-00
.rw-rw-r-- 23k thomasf 23 Jan 22:47 profile.zip.2019-12-19T01-03-14.950275+01-00
.rw------- 56k thomasf 23 Jan 22:47 profiling-127.0.0.1:9000.pprof
lrwxrwxrwx  11 thomasf 23 Jan 22:49 symling -> profile.zip
```

**Comment by ariasuni** [comment]
Do you think it’s possible for you to resolve conflicts? I’d be interested to review and merge, if there’s no slowdown in other situations. Did you make other measures?

**Comment by saethlin** [comment]
Doing some housekeeping on my open PRs. I don't really know how I lost track of this, but to be fair I didn't really know how to use GitHub back when I opened this.

I have noticed that exa has some parallelism now. Is this sort of change still of interest? I no longer have access to an environment which a terribly slow filesystem to do such benchmarking, but I'm happy to do something here if there is still interest.

**Comment by ariasuni** [comment]
To be honest I’m not really sure if your work is still relevant — I think this PR was open before I started contributing seriously to this project —, do you think you can try to figure out if this PR may still be useful or not? Since performance is still a regular complaint for this project, I think it would worth it.

**Comment by saethlin** [comment]
I've been looking at this in my notifications for a while now and I've decided I don't have the time/energy for it, but I can offer some suggestions.

On systems with a fast filesystem, this will not help. If users are looking at CPU time as opposed to wall time, this will also not help. Where this _does_ make a big difference is very slow (usually networked) filesystems. When I started this PR such filesystems were important to me because I was doing all my work on an HPC cluster, so I was either on a big NFS system or a big Lustre system. But not anymore.

In any case, the fastest option is to not call any of the `stat`-family syscalls at all (if you're using a modern Linux only `statx` is called). The syscall that paginates through the entries of a directory on Linux is `getdents`/`getdents64`, and it usually contains the entry type (directory, file, link, etc) that you want to do output coloring. But the portable POSIX interface and the Rust standard library do not make this information available to you, and they force you do a `stat` call on every entry. I eventually implemented my own Linux-only `ls` to take advantage of this, the code that does the `getdents` handling is here and you are of course welcome to it: https://github.com/saethlin/veneer/blob/8f2b960f5ff5c46c26d233e07658224b56a902bb/src/fs/directory.rs

**Comment by ariasuni** [comment]
Thanks a lot for this detailed report and for your initial work!

**Pull request closed without merging**
