### PR TITLE
Add support for extended attributes

### PR DESCRIPTION
**Pull request by nwin**
exa now matches the behavior of `ls` on OSX. In theory this could also work on Linux but the API is different and I can’t test it. It should be relatively easy to implement it for Linux as the rust API is already generalized.

I haven't tested it unter linux but it should work since the feature is a no-op there.

### CODE REVIEW

**Comment by nwin** [comment]
I’ve no clue why travis failed, maybe rustc is too old.

**Comment by ogham** [comment]
I'm with Travis on this one - you need to bring the xattr module into scope before you can use it in tests. Try adding `use xattr;` into the block of `use`s on line 476, then test again.

**Comment by nwin** [comment]
Of course… :(

**Comment by ogham** [comment]
>> #25

**Pull request closed without merging**
