### PR TITLE
Add some icons for files

### PR DESCRIPTION
**Pull request by horosgrisa**

### CODE REVIEW

**Comment by dylanjm** [comment]
Would love to see these icons added. Any ETA on merging this?

**Comment by horosgrisa** [comment]
image

This commit cantain only new icons.

**Comment by dylanjm** [comment]
@horosgrisa Yeah, they look awesome for some of the files I use.

**Comment by dylanjm** [comment]
@horosgrisa how did you get your icons the same color as your names?

**Comment by horosgrisa** [comment]
@dylanjm It's the default behaviour, but I use good clicolor config. Can you show a screenshot with your exa output?

**Comment by horosgrisa** [comment]
@dylanjm I use this dircolor config https://github.com/zpm-zsh/dircolors-material

**Comment by dylanjm** [comment]
I'll have to look into dircolor. This is what mine currently looks like:

image

**Comment by ogham** [comment]
Thanks!

**Comment by horosgrisa** [comment]
@ogham Wow, you are really fast))

**Comment by ogham** [comment]
You can't rush art

**Comment by horosgrisa** [comment]
@ogham Haha. Please, see https://github.com/ogham/exa/issues/559

**Pull request merged**
