### PR TITLE
Add support for suppressing table columns

### LINKED ISSUE #226: Hide user with --long
I'd like to hide the `user` column with `--long` enabled, but there does not seem to be a way to do that?

### PR DESCRIPTION
**Pull request by 0rvar**
Makes it possible to get sweet lists like this:

Screenshot 2019-08-29 at 14 35 14

Resolves #226

### CODE REVIEW

**Comment by thomasf** [comment]
This patch does not update `exa --help`

**Comment by antonmedv** [comment]
This is be cool to see.

**Comment by 0rvar** [comment]
> This patch does not update `exa --help`, shell completion scripts or man page

Thanks for pointing this out.
* Updated --help, covered by xtests
* Updated man page and verified with `nroff -man contrib/man/exa.1`
* Updated shell completions, verified the Fish completions but could not get bash/zsh completions working as I don't use those shells enough to know how to drop in temporary completions.

@ogham Is this something you want merged at all?

**Comment by ogham** [comment]
Thanks for this! 👍 

I expect that exa should really have generic arguments for all its parameters, but this is a great start.

**Comment by learn2reid** [comment]
not working

**Comment by 0rvar** [comment]
> not working

Thank you for your feedback.

Let's lock this PR against further comments

**Pull request merged**
