### PR TITLE
Update Vue's icon to display properly under the new version of Nerdfont

### PR DESCRIPTION
**Pull request by ringhol**
before：
image
after：
image

I use nerdfonts 3.0

### CODE REVIEW

**Comment by yangxyo** [comment]
+1

**Comment by ariasuni** [comment]
Could you do the same for other glyphs as well? There’s a translation table [in this comment](https://github.com/ryanoasis/nerd-fonts/issues/1059#issuecomment-1404891287). It seems like there are a dozen code points to change.

**Comment by semtor** [comment]
> Could you do the same for other glyphs as well? There’s a translation table [in this comment](https://github.com/ryanoasis/nerd-fonts/issues/1059#issuecomment-1404891287). It seems like there are a dozen code points to change.你能对其他字形也做同样的事情吗？评论里有翻译表。似乎有十几个代码点需要更改。

image

I just printed all the icons in [src/output/icons.rs](https://github.com/ogham/exa/blob/master/src/output/icons.rs) . While I'm using nerdfont 3.0, it seems like all other icons are displayed fine

**Comment by ariasuni** [comment]
Closing this, exa is unmaintained (see https://github.com/ogham/exa/issues/1243), and #1196 has been merged in [the active fork eza](https://github.com/eza-community/eza). Thanks anyway!

**Pull request closed without merging**
