### PR TITLE
documentation: add hint how to install exa on Android / Termux

### PR DESCRIPTION
**Pull request by alexanderadam**
Hi Benjamin,

thank you so much for creating `exa` :pray:

### CODE REVIEW

**Comment by ogham** [comment]
Thanks!

I went on the [termux website](https://wiki.termux.com/wiki/Package_Management) and found this:

> We strongly recommend to use a pkg utility instead of apt directly. 

Would it be better to use `pkg` here?

**Comment by alexanderadam** [comment]
> Would it be better to use `pkg` here?

You are absolutely right. Wasn't aware of that. I changed it accordingly :+1:

**Comment by ogham** [comment]
Thanks!

**Comment by alexanderadam** [comment]
I have to thank you! `exa` is _really_ great! :heart:

**Pull request merged**
