### PR TITLE
Update filetype.rs

### PR DESCRIPTION
**Pull request by pskuza**
Added a few video and audio extensions

### CODE REVIEW

**Comment by ogham** [comment]
Neat. I'm not 100% about `.ts` because I've seen it used for TypeScript, but I'll include it anyways.

**Comment by hoodie** [comment]
`.ts` is most definitely typescript

**Comment by pskuza** [comment]
.ts can also be transport stream which is common for linux setup boxes that record tv stations, you'll end up with a .ts file.

**Comment by hoodie** [comment]
Right, I kinda assume more of exas users having to do with typescript then with that format.

**Pull request merged**
