### PR TITLE
--icons option

### PR DESCRIPTION
**Pull request by asoderman**
I added an option to have [nerd fonts](https://nerdfonts.com/#cheat-sheet) appear before each entry in grid mode (edit: now in lines and detail mode as well).

relevant issues: #357 #191

### CODE REVIEW

**Comment by kutsan** [comment]
I compiled your branch and it's looking awesome. It should be merged IMO. Thanks!

**Comment by cserb** [comment]
I also tried it it out, but it doesn't seem to support `long view` or even `-1`

**Comment by asoderman** [comment]
Yeah I wanted to see if I had the right approach before adding it to the other modes. Check it out now 👍

**Comment by cserb** [comment]
Looks good! :+1:

**Comment by kutsan** [comment]
I think there should be also a way to tweak icons. For example I don't like current folder node icon, and I want to make it something else.

**Comment by phaazon** [comment]
Works like a charm! Thanks for doing it!

**Comment by hoop33** [comment]
I recently discovered `exa` and went to add exactly this functionality, and was delighted that someone already has. Any chance this PR can be merged?

**Comment by luisdavim** [comment]
Any chances of this getting merged?

**Comment by luisdavim** [comment]
@asoderman can you rebase and address the conflicts?

**Comment by BarbzYHOOL** [comment]
@ogham have you seen that? :)

**Comment by jcklpe** [comment]
Would love to see this feature added.

**Comment by SakiiR** [comment]
Hope everything is going fine here 👍

**Comment by jcklpe** [comment]
Just for future travelers ease of use, just go to the pull request branch and clone it down and build it using rust. very easy to do

https://github.com/asoderman/exa.git

**Comment by ogham** [comment]
Thanks! Sorry about the wait. 👍

**Comment by quintrino** [comment]
So I've just installed this now using brew install exa --head but I'm getting a bunch of Question Mark in Boxes instead of icons. 

The font I'm currently using is Source Code Pro for Powerline, which I assumed was nerdy enough to have icons included. 

What fonts is this compatible with?

**Comment by GitSquared** [comment]
@quintrino You should take a look at ryanoasis/nerd-fonts - I believe they have a patched version of Source Code Pro already, if not, it's easy to patch it yourself.

**Comment by lilyball** [comment]
This PR didn't update the manpage.

**Comment by lilyball** [comment]
Or the shell completions.

**Comment by SkYNewZ** [comment]
It doesn't seem to work for me…

image

**Comment by lilyball** [comment]
@SkYNewZ You need to configure your terminal to use the right fonts. From the PR description, what you want is [Nerd Fonts](https://nerdfonts.com).

**Comment by cserb** [comment]
> Hey to get this feature do I need to re-download and install exa or does it have some kind of auto updater? Or is there a flag I need to use?

you have to use exa with the `--icons` option `exa -la --icons`

also you need to have nerd fonts installed

**Pull request merged**
